// reddit-hub-post/src/app/components/register/register.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  user = {
    userName: "",
    userLastName: "",
    userBirth: "",
    gender: "",
    phoneNumber: "",
    status: "Active",
    email: "",
    password: ""
}

  constructor() { }

  ngOnInit(): void {
  }

  signUp(){
    console.log(this.user);
    
  }

}

<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Register and be part of us.</h5>
            </div>
            <div class="card-body">
                <form (submit)="signUp()">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label htmlFor="inputNombre">Nombres</label>
                            <input required type="text" [(ngModel)]="user.userName" class="form-control" id="inputNombre" name="name" />
                        </div>
                        <div class="form-group col-md-6">
                            <label htmlFor="inputApellido">Apellidos</label>
                            <input required type="text" [(ngModel)]="user.userLastName" class="form-control" id="inputApellido" name="lname" />
                        </div>
                        <div class="form-group col-md-6">
                            <label htmlFor="inputTelefono">Date birth</label>
                            <input required type="date" [(ngModel)]="user.userBirth" class="form-control" id="inputEmail4" name="email" name="email" />
                        </div>
                        <div class="form-group col-md-6">
                            <label htmlFor="inputTelefono">Telefono</label>
                            <input required type="text" [(ngModel)]="user.phoneNumber" class="form-control" id="inputTelefono" name="phone" />
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label htmlFor="inputApartment">Gender</label>
                            <select id="inputApartment" [(ngModel)]="user.gender" class="form-control" name="apartment">
                                <option value>Male</option>
                                <option>Female</option>
                                <option>Non binary</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label htmlFor="inputTelefono">Email</label>
                            <input required type="text" [(ngModel)]="user.email" class="form-control" id="inputEmail4" name="email" name="email" />
                        </div>
                        <div class="form-group col-md-6">
                            <label htmlFor="inputPass">Password</label>
                            <input required type="password" [(ngModel)]="user.password" class="form-control" id="inputPass" name="password" />
                        </div>
                        <div class="form-group col-md-6">
                            <label htmlFor="inputPass">Repeat password</label>
                            <input required type="password" class="form-control" id="inputPass" name="repeatPassword" />
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

// reddit-clone/src/component/Register.jsx
import React from 'react';
import '../assets/styles/component/Register.css';

const Register = () => (
        <div id= "container_register" className= "container p-4">

            <div id="card_register" className="row">
                <div className="col-md-10">
                    <div className="card">
                        <div id="card_title_register" className="card-header">
                            <h5 className="card-title" >Register and be part of us</h5>
                        </div>
                    </div>
                </div>
            </div>

            <div id="form_signup">
                <form action="/auth/signup" method="POST" encType="multipart/form-data">
                    <div className="form-row">
                        <div className="form-group col-md-5">
                            <label htmlFor="inputNombre">Nombres</label>
                            <input required type="text" className="form-control" id="inputNombre" name="name" />
                        </div>
                        <div className="form-group col-md-5">
                            <label htmlFor="inputApellido">Apellidos</label>
                            <input required type="text" className="form-control" id="inputApellido" name="lname" />
                        </div>
                        <div className="form-group col-md-5">
                            <label htmlFor="inputTelefono">Email</label>
                            <input required type="email" className="form-control" id="inputEmail4" name="email" name="email" />
                        </div>
                        <div className="form-group col-md-5">
                            <label htmlFor="inputTelefono">Telefono</label>
                            <input required type="text" className="form-control" id="inputTelefono" name="phone" />
                        </div>
                    </div>
                    <div className="form-row">
                        <div className="form-group col-md-5">
                            <label htmlFor="inputApartment">Gender</label>
                            <select id="inputApartment" className="form-control" name="apartment">
                                <option value>Male</option>
                                <option>Female</option>
                                <option>Non binary</option>
                            </select>
                        </div>
                        <div className="form-group col-md-5">
                            <label htmlFor="inputTelefono">Email</label>
                            <input required type="text" className="form-control" id="inputEmail4" name="email" name="email" />
                        </div>
                        <div className="form-group col-md-5">
                            <label htmlFor="inputPass">Password</label>
                            <input required type="password" className="form-control" id="inputPass" name="password" />
                        </div>
                        <div className="form-group col-md-5">
                            <label htmlFor="inputPass">Repeat password</label>
                            <input required type="password" className="form-control" id="inputPass" name="repeatPassword" />
                        </div>
                    </div>
                    <button type="submit" className="btn btn-success">Guardar</button>
                </form>


            </div>
        </div>
);


export default Register;
